### ISSUE TITLE
如果 client 为 mysql2 的时候会报错.

### ISSUE THREAD

**Issue by hzgotb** [waitingsong/kmore#1]
https://github.com/waitingsong/kmore/blob/dde1face3f84fd91d380065240ef2419d156e25d/packages/egg-kmore/src/lib/index.ts#L64

mysql2 返回的结构是 [TextRow[], ColumnDefinition[]]。

应该判断 client 是不是 mysql2 。
然后
```ts
app.beforeStart(async () => {
  const isMySQL2 = clientOpts.knexConfig.client === 'mysql2';
  const result = await client.dbh.raw('SELECT now() AS currentTime;');
  const rows = isMySQL2 ? result[0] : result.rows;
  count += 1;
  assert(rows[0].currentTime, 'Should retrieve current time from connecting database, but got invalid.');
  app.coreLogger.info(`[egg-kmore] instance[${count}] status connected, db currentTime: ${rows[0].currentTime}`);
});
```

然后 SQL 里写的是 currentTime 。下面引用的是 currenttime 。

**Comment by waitingsong** [comment]
fixed.

**Comment by hzgotb** [comment]
为什么要为 mysql 和 pg 跳过判断连接状态？是暂时性跳过吗？

**Comment by waitingsong** [comment]
修改为仅当pg, mysql, mysql2 时才执行 sql 检测，其它数据库不检测(因为没测试过是否支持 now() 命令)。
 那看来还得修改。

**Comment by waitingsong** [comment]
细节是魔鬼， mysql/mariadb 无处不是坑。
- 不支持 `DROP TABLE tb_user CASCADE`，必须先删除外键关联 https://mariadb.com/kb/en/drop-table/
- 如果 `tb_user` 表无数据，那么执行 `SELECT now() FROM tb_user` 返回空，如果表非空那么就能返回正确值。即便通过数据库客户端来执行此 SQL，也是同样问题。

真是奇葩的存在。

**Comment by hzgotb** [comment]
mysql2 可以执行 `select now() AS currenttime`，是没问题的。
`SELECT now() FORM tb_user` 是因为表里面没有这个字段。执行这条的意图是什么。

**Comment by waitingsong** [comment]
> mysql2 可以执行 select now() AS currenttime，是没问题的。

确认是没问题的。

> SELECT now() FORM tb_user 是因为表里面没有这个字段。执行这条的意图是什么

哈，我明白为啥返空了
比如查询记录时额外生成一个时间戳字段
```sql
SELECT uid, now() FROM tb_user
```
如果表无记录，那么查询结果自然空，于是肯定不会有 now() 字段的输出。于是当执行
```sql
SELECT now() FROM tb_user
```
的时候也按照上面的逻辑来处理了， 同样的执行逻辑还有：
```sql
SELECT MD5('abc') FROM tb_user;
SELECT CURRENT_TIMESTAMP FROM tb_user;
```
看来 mysql 开发者的脑回路和我不一样……

**Comment by waitingsong** [comment]
假定 tb_user.name 字段为 string 类型，那么以下两条 SQL 的逻辑是接近的：
```sql
SELECT MD5(name) FROM tb_user;
SELECT MD5('ab') FROM tb_user;
```
对于第二条 SQL 返空，不符合常理认知。因为在代码开发过程中是可能会出现第二条类型 SQL 这种情况。
